apiVersion: v1
kind: Service
metadata:
    labels:
      app: juice-shop
    name: juice-shop-public-service
    namespace: default
    selfLink: /api/v1/namespaces/default/services/juice-shop-public-service
spec:
    clusterIP: 100.66.141.106
    externalTrafficPolicy: Cluster
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: juice-shop
    type: LoadBalancer
